spring:
  application:
    name: feng-ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.feng.fengaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn